// Code generated by hertz generator.

package user

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getuserconversationsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getuserinfoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _searchuserMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _addfriendMw() []app.HandlerFunc {
	// your code...
	return nil
}
