// Code generated by hertz generator.

package chat

import (
	"core/biz/jwt"

	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	jwtAuth := jwt.JwtMiddleware()
	return []app.HandlerFunc{jwtAuth}
}

func _wsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _connectchatwsMw() []app.HandlerFunc {
	// your code...
	return nil
}
