// Code generated by hertz generator.

package chat

import (
	"core/biz/jwt"

	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...

	return nil
}

func _wsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _connectchatwsMw() []app.HandlerFunc {
	// your code...
	// jwtAuth := jwt.JwtMiddleware()
	// return []app.HandlerFunc{jwtAuth}
	return nil
}

func _chatMw() []app.HandlerFunc {
	// your code...
	// jwtAuth := jwt.JwtMiddleware()
	// return []app.HandlerFunc{jwtAuth}
	return nil
}

func _conversationsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getconversationMw() []app.HandlerFunc {
	// your code...
	jwtAuth := jwt.JwtMiddleware()
	return []app.HandlerFunc{jwtAuth}
	// return nil
}
