services:
  youchat:
    build: .
    ports:
      - 5050:5050
    environment:
      - APP_HERTZ_ADDRESS=":5050"
      - APP_MYSQL_HOST=mysql
      - APP_MYSQL_PORT=3306
      - APP_MYSQL_DATABASE=gorm
      - APP_MYSQL_USERNAME=gorm
      - APP_MYSQL_PASSWORD=gorm
      - APP_REDIS_ADDRESS=redis:6379
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./logs:/bin/logs

  mysql:
    image: 'mysql:latest'
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=gorm
      - MYSQL_USER=gorm
      - MYSQL_PASSWORD=gorm
      - MYSQL_ROOT_PASSWORD=root  # 设置固定的root密码而不是随机
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  redis:
    image: 'redis:latest'
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s

volumes:
  mysql_data: