// Code generated by hertz generator.

package group

import (
	"core/biz/jwt"

	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _groupMw() []app.HandlerFunc {
	// your code...
	jwtAuth := jwt.JwtMiddleware()
	return []app.HandlerFunc{jwtAuth}
	// return nil
}

func _creategroupMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _searchgroupMw() []app.HandlerFunc {
	// your code...
	return nil
}
