// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	auth "core/biz/router/auth"
	chat "core/biz/router/chat"
	group "core/biz/router/group"
	user "core/biz/router/user"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	group.Register(r)

	user.Register(r)

	chat.Register(r)

	auth.Register(r)
}
